# Generated by Django 3.2.14 on 2022-07-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocokm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationinfo',
            name='address_6',
        ),
        migrations.RemoveField(
            model_name='locationinfo',
            name='likeCount',
        ),
    ]
